favouritesubject=("English")
print(favouritesubject)
favouritefilm=("dumb and dumber")
print(favouritefilm)


mom=("გურანდა")
dad=("გიორგი")
uncledadsside=("გუგა")
unclemomsside=("გიორგი")
cousindadsside=("სესილი")
cousinsmomsside=("გიო&ანა")
sister=("ელენე")
auntdadssister=("ლიკა")
grandmadadsside=("მადონა")
grandmamomsside=("იამზე")
grandpadadsside=("გურნგენი")
auntdadsside=("თამუნა")
auntmomsside=("სოფო")
print(auntmomsside)
print(auntdadsside)
print(grandpadadsside)
print(grandmamomsside)
print(grandmadadsside)
print(auntdadssister)
print(sister)
print(cousinsmomsside)
print(cousindadsside)
print(unclemomsside)
print(uncledadsside)
print(mom)
print(dad)